apiVersion: v1
kind: Service
metadata:
  name: chatbot-conversations
spec:
  type: ClusterIP
  ports:
    - port: 8082
      protocol: TCP
      targetPort: server
  selector:
    app: chatbot-conversations