version: "2"

networks:
  default:
    external:
      name: chatbot

services:
  chatbot-service:
    image: jurebevc/chatbot-conversations
    container_name: chatbot-conversations
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8082:8082
    environment:
      - DB_PATH=mysql+pymysql://root:123@db:3306/chatbot
      #  - DB_PATH=mysql+pymysql://sql7379575:MutA4e46L1@sql7.freesqldatabase.com/sql7379575